include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  errors:
    invalid_annotation_target: ignore
    type_annotate_public_apis: ignore
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, packages/**.freezed.dart, packages/**.g.dart, packages/**.firestore_converter.dart]