name: cheaters_dice
description: Cheaters Dice
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.3
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.7.6
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_login: ^5.0.0
  freezed_annotation: ^2.4.1
  game_repository:
    path: packages/game_repository
  intl: ^0.19.0
  json_annotation: ^4.9.0
  meta: ^1.12.0
  wolt_modal_sheet: ^0.6.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.11
  firestore_converter_generator: 
    git: 
      url: https://github.com/ericpark/firestore_converter.git
      path: packages/firestore_converter_generator
      ref: main
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/