name: cheaters_dice
description: Cheaters Dice
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  animated_text_kit: ^4.2.2
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.3
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.7.6
  dice_icons: ^0.1.7
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_login: ^5.0.0
  flutter_native_splash: ^2.4.0
  freezed_annotation: ^2.4.1
  game_repository:
    path: packages/game_repository
  go_router: ^14.1.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  meta: ^1.12.0
  wolt_modal_sheet: ^0.6.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.10
  firestore_converter_generator: 
    git: 
      url: https://github.com/ericpark/firestore_converter.git
      path: packages/firestore_converter_generator
      ref: main
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  #remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    #image_path: "path/to/image.png"
    #background_color: "#hexcode"
    #theme_color: "#hexcode"
  windows:
    generate: true
    #image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    #image_path: "path/to/image.png"

flutter_native_splash:
  color: "#fefefe"
  image: assets/icons/logo.png
  branding: assets/icons/brand_logo_sm.png
  branding_mode: bottom
