name: game_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: none

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.1
  equatable: ^2.0.5
  firebase_core: ^3.1.0
  firestore_converter: ^1.0.9
  flutter: 
   sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.4.8
  coverage: ^1.0.3
  firestore_converter_generator: 
    git: 
      url: https://github.com/ericpark/firestore_converter.git
      path: packages/firestore_converter_generator
      ref: main
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.16.4  
  very_good_analysis: ^5.1.0
  
flutter:
 generate: true
